### ISSUE TITLE
Dica

### ISSUE THREAD

**Issue by hisirdox** [IltonBJSilva/resolucao-exercicio-uri#1]
### Olá, @IltonBJSilva.
Que tal se ao invés de usar este repositório, vc não adiciona um link no perfil do **github** para seu perfil do **Uri**?

**Comment by IltonBJSilva** [comment]
interessante isso muito obrigado irei ver

Em qua, 5 de jun de 2019 às 17:14, Alan C. <notifications@github.com>
escreveu:
